---
name: App-Open
version: 0.0.1
author:
  - 'Erik Hollensbe <erik@hollensbe.org>'
abstract: Library to drive the 'openit' command line tool
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
build_requires:
  Getopt::Long: 0
  Test::Exception: 0
  Test::More: 0
  YAML::Syck: 0
  version: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
